name: skyscrapeapi
description: SkyMobile API is the API that was taken from the original SkyMobile app. SkyMobile API allows easy Skyward access for developers.
version: 3.0.0+13
homepage: https://github.com/skuweakyskies/SkyScrapeAPI

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  http: ^0.12.0+2
  html: ^0.14.0+2

dev_dependencies:
  test: ^1.8.0