name: skyscrapeapi
description: SkyMobile API is the API that was taken from the original SkyMobile app. SkyMobile API allows easy Skyward access for developers.
version: 2.3.6+1
author: Hunter Han <hunter.han@gmail.com>
homepage: https://github.com/skuweakyskies/SkyScrapeAPI

environment:
  sdk: ">=1.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+2
  html: ^0.14.0+2

dev_dependencies:
  test: ^1.8.0
